export const URLS = {
	HOME: '/',
	ADMIN_PANEL_URL: '/admin',
	AUTH: '/auth',
	MY_ORDERS: '/my-orders',
	CHECKOUT: '/checkout',
	AUTH_ACCESS_TOKEN: '/auth/login/access-token',
	CATEGORIES: '/categories',
	CATEGORY: '/category',
	CATEGORY_BY_SLUG: '/categories/by-slug',
	REVIEWS: '/reviews',
	REVIEW: '/review',
	REVIEWS_LEAVE: '/reviews/leave',
	USERS: '/users',
	USERS_PROFILE: '/users/profile',
	USERS_PROFILE_FAVORITES: '/users/profile/favorites',
	STATISTICS_MAIN: '/statistics/main',
	ORDERS: '/orders',
	ORDER: '/order',
	ORDERS_BY_USER: '/orders/by-user',
	PAYMENT: '/payment',
	PRODUCTS: '/products',
	PRODUCT: '/product',
	PRODUCTS_SIMILAR: '/products/similar',
	PRODUCTS_BY_SLUG: '/products/by-slug',
	PRODUCTS_BY_CATEGORY: '/products/by-category',
	FAVORITES: '/favorites',
	EXPLORER: '/explorer',
}
export const getSiteUrl = () => process.env.APP_URL as string
export const getAdminUrl = (path = '') => `${URLS.ADMIN_PANEL_URL}${path}`
