export const URLS = {
	AUTH_LOGIN_ACCESS_TOKEN: 'auth/login/access-token',
	AUTH_LOGIN: '/auth/login',
	AUTH: '/auth',
	AUTH_REGISTER: '/auth/register',
	AUTH_LOGOUT: '/auth/logout',
	MENU_ITEM: '/menu-item',
	MENU_ITEM_COPY: '/menu-item/copy',
	PURCHASING: '/purchasing',
	MENU_ITEM_EXCEL: '/menu-item/excel',
	MENU_ITEM_ORDER_UPDATE: '/menu-item/order/update',
	DISHES: '/dishes',
	DISHES_EXCEL: '/dishes/excel',
	DISHES_BY_NAME: '/dishes/by-name',
	DISHES_BY_NAME_CONTAINS: '/dishes/findByNameContains',
	INSTITUTIONS: '/institutions',
	INSTITUTIONS_BY_NAME: '/institutions/by-name',
	INSTITUTIONS_BY_NAME_CONTAINS: '/institutions/findByNameContains',
	INSTITUTIONS_BY_SLUG: '/institutions/by-slug',
	INGREDIENTS: '/ingredients',
	INGREDIENTS_BY_NAME: '/ingredients/by-name',
	INGREDIENTS_BY_NAME_CONTAINS: '/ingredients/findByNameContains',
	INGREDIENTS_BY_SLUG: '/ingredients/by-slug',
	INGREDIENT_ALIAS: '/ingredient-alias',
	INGREDIENT_ALIAS_BY_NAME: '/ingredient-alias/ingredient',
	DISHCATEGORIES: '/dish-categories',
	DISHCATEGORIES_BY_NAME: '/dish-categories/by-name',
	DISHCATEGORIES_BY_NAME_CONTAINS: '/dish-categories/findByNameContains',
	DISHCATEGORIES_BY_SLUG: '/dish-categories/by-slug',
	MEALS: '/meals',
	MEAL_BY_SLUG: '/meals/by-slug',
	MEAL_BY_NAME_CONTAINS: '/meals/findByNameContains',
	MENU_ITEM_BY_INSTITUTION: '/menu-item/by-institution',
	USER_PROFILE: '/user/profile',
	MEALCONSUMPTIONS: '/meal-consumption',
	MEAL_CONSUMPTION_ITEM_BY_INSTITUTION: '/meal-consumption/by-institution',
}

