export const URLS = {
	AUTH_LOGIN_ACCESS_TOKEN: '/auth/login/access-token',
	AUTH_LOGIN: '/auth/login',
	AUTH_LOGIN_PHONE: '/auth/login/phone',
	AUTH: '/auth',
	AUTH_REGISTER: '/auth/register',
	AUTH_REGISTER_PHONE: '/auth/register/phone',
	AUTH_LOGOUT: '/auth/logout',
	AUTH_GOOGLE: '/auth/google',
	AUTH_GOOGLE_CALLBACK: '/auth/google/callback',
	MENU_ITEM: '/menu-item',
	MENU_ITEM_COPY: '/menu-item/copy',
	PURCHASING: '/purchasing',
	MENU_ITEM_EXCEL: '/menu-item/excel',
	MENU_ITEM_ORDER_UPDATE: '/menu-item/order/update',
	DISHES: '/dishes',
	DISHES_EXCEL: '/dishes/excel',
	DISHES_BY_NAME: '/dishes/by-name',
	DISHES_BY_NAME_CONTAINS: '/dishes/findByNameContains',
	DISH_ALIAS: '/dish-aliases',
	DISH_ALIAS_BY_NAME: '/dish-aliases/dish',

	DISHCATEGORIES: '/dish-categories',
	DISHCATEGORIES_BY_NAME: '/dish-categories/by-name',
	DISHCATEGORIES_BY_NAME_CONTAINS: '/dish-categories/findByNameContains',
	DISHCATEGORIES_BY_SLUG: '/dish-categories/by-slug',
	MEALS: '/meals',
	MEAL_BY_SLUG: '/meals/by-slug',
	MEAL_BY_NAME_CONTAINS: '/meals/findByNameContains',
	MENU_ITEM_BY_INSTITUTION: '/menu-item/by-institution',
	USER_PROFILE: '/user/profile',
	MEALCONSUMPTIONS: '/meal-consumption',
	RETAILSALES: '/retail-sales',
	WAREHOUSES: '/warehouses',
	WAREHOUSES_BY_NAME_CONTAINS: '/warehouses/findByNameContains',
	STOCK_TRANSFERS: '/stock-transfers',
	STOCK_TRANSFERS_BY_RANGE: '/browser/stockTransferByDateRange',
	MARKET_ALL: '/market/all',

	// Signal endpoints
	SIGNALS: '/signals',
	VOLATILITY_SIGNALS: '/volatility-spike-signals',
	VOLUME_SIGNALS: '/trading-signals/volume',
	FUNDING_SIGNALS: '/trading-signals/funding',
	GAINER_SIGNALS: '/gainer-signals',
	LOSER_SIGNALS: '/loser-signals',
	TOP_GAINERS: '/trading-signals/gainers',
	TOP_LOSERS: '/trading-signals/losers',
	TELEGRAM_SIGNALS: '/telegram-signals/parsed',
	TELEGRAM_CHANNEL: '/telegram-channel',
	TELEGRAM_CHANNELS: '/telegram-channels',
	TELEGRAM_CHANNELS_EXCEL: '/telegram-channels/excel',
	SYMBOLS_TO_REDIS: '/symbol-to-redis',
	SYMBOLS_TO_REDIS_EXCEL: '/symbols/excel',
} as const

